data:
  source_image:
    type: image
    path: 
      https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png
    name: Lena (Source)
    description: Classic test image downloaded from URL
  grayscale_image:
    type: image
    path: data/grayscale.png
    name: Grayscale
    description: Image converted to grayscale
  edges_image:
    type: image
    path: data/edges.png
    name: Edge Detection
    description: Canny edge detection result
  blurred_image:
    type: image
    path: data/blurred.png
    name: Gaussian Blur
    description: Blurred version of grayscale image
parameters:
  blur_radius: 15
  edge_threshold_low: 50
  edge_threshold_high: 150

pipeline:
- name: grayscale
  task: tasks/grayscale.py
  inputs:
    image: $source_image
  outputs:
    -o: $grayscale_image
- name: edge_detect
  task: tasks/edge_detect.py
  inputs:
    image: $grayscale_image
  outputs:
    -o: $edges_image
  args:
    --low: $edge_threshold_low
    --high: $edge_threshold_high
- name: blur
  task: tasks/blur.py
  inputs:
    image: $grayscale_image
  outputs:
    -o: $blurred_image
  args:
    --radius: $blur_radius
layout:
  grayscale:
    x: 648
    y: 508
  edge_detect:
    x: 1173
    y: 383
  blur:
    x: 1166
    y: 635
  param_blur_radius:
    x: 850
    y: 740
  param_edge_threshold_low:
    x: 830
    y: 363
  param_edge_threshold_high:
    x: 807
    y: 220
  data_source_image:
    x: 422
    y: 480
  data_grayscale_image:
    x: 894
    y: 497
  data_edges_image:
    x: 1443
    y: 388
  data_blurred_image:
    x: 1435
    y: 675
