data:
  # Input
  raw_csv:
    type: csv
    path: data/raw.csv
  validated_csv:
    type: csv
    path: data/validated.csv
  stats_json:
    type: json
    path: data/stats.json
  clean_csv:
    type: csv
    path: data/clean.csv
  final_report:
    type: json
    path: data/final_report.json
parameters:
  outlier_threshold: 1.5
  num_rows: 100

pipeline:
  # Ingestion steps grouped together
- group: ingestion
  steps:
  - name: generate_data
    task: tasks/generate_data.py
    outputs:
      --output: $raw_csv
    args:
      --rows: $num_rows
  - name: load_data
    task: tasks/load_data.py
    inputs:
      raw: $raw_csv
    outputs:
      --output: $validated_csv
- group: analysis
  steps:
  - name: compute_stats
    task: tasks/compute_stats.py
    inputs:
      data: $validated_csv
    outputs:
      --output: $stats_json
  - name: filter_outliers
    task: tasks/filter_outliers.py
    inputs:
      data: $validated_csv
    outputs:
      --output: $clean_csv
    args:
      --threshold: $outlier_threshold
- name: merge_results
  task: tasks/merge_results.py
  inputs:
    stats: $stats_json
    clean_data: $clean_csv
  outputs:
    --output: $final_report
